apiVersion: v1
kind: Pod
metadata:
  name: logstash-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: logstash
    image: raquette/logstash-oss:7.9.3
    imagePullPolicy: Always
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  hostNetwork: true
  dnsPolicy: Default

